spring:
  datasource:
    c3p0:
     driverClass: com.mysql.jdbc.Driver
     jdbcUrl: jdbc:mysql://localhost:3306/springboot_db
     user: root
     password: root
     minPoolSize: 10
     maxPoolSize: 25
     initialPoolSize: 10
server:
  port: 8888
  address: 127.0.0.2
  connection-timeout: 1000
  context-path: /boot
mybatis:
  typeAliasesPackage: com.itheima.pojo
  configLocation: classpath:mybatis-config.xml
  mapperLocations: classpath:mappers/**/*Mapper.xml